# Generated by Django 3.2 on 2021-05-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('publication_date', models.DateField(verbose_name='Дата создания')),
                ('num_of_chapters', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.author', verbose_name='Автор')),
                ('category', models.ManyToManyField(related_name='comics', to='base.Category', verbose_name='Категория')),
                ('genre', models.ManyToManyField(to='base.Genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.publisher', verbose_name='Издатель')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.rating', verbose_name='Рейтинг')),
                ('type', models.ManyToManyField(related_name='comics', to='base.Type', verbose_name='Тип')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('publication_date', models.DateField(verbose_name='Дата создания')),
                ('num_pages', models.IntegerField(default=0, verbose_name='Количество страниц')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.author', verbose_name='Автор')),
                ('genre', models.ManyToManyField(to='base.Genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.publisher', verbose_name='Издатель')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.rating', verbose_name='Рейтинг')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
