# Generated by Django 3.2 on 2021-05-14 11:57

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commentforcomics'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='book storage', validators=[utils.validators.validate_extension_for_book]),
        ),
    ]
