# Generated by Django 3.2 on 2021-05-14 12:02

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comics storage', validators=[utils.validators.validate_extension_for_comics]),
        ),
    ]
